import os
from datetime import datetime
from config import Config

def generate_pdf_report(user, prediction=None, resume_data=None, recommendations=None, report_type="Expertise Report"):
    """
    Generates a PDF report summarizing AI prediction, skills, resume analysis, or recommendations.
    Returns relative report filepath.
    """
    os.makedirs(Config.REPORT_FOLDER, exist_ok=True)
    filename = f"{report_type.lower().replace(' ', '_')}_{user.id}_{int(datetime.utcnow().timestamp())}.pdf"
    filepath = os.path.join(Config.REPORT_FOLDER, filename)
    
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib import colors

        doc = SimpleDocTemplate(filepath, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        styles = getSampleStyleSheet()
        
        # Custom Styles
        title_style = ParagraphStyle('DocTitle', parent=styles['Heading1'], fontSize=22, textColor=colors.HexColor('#1E293B'), spaceAfter=10)
        subtitle_style = ParagraphStyle('SubTitle', parent=styles['Normal'], fontSize=11, textColor=colors.HexColor('#64748B'), spaceAfter=15)
        heading_style = ParagraphStyle('SectionHeading', parent=styles['Heading2'], fontSize=14, textColor=colors.HexColor('#2563EB'), spaceBefore=12, spaceAfter=8)
        body_style = ParagraphStyle('BodyTextCustom', parent=styles['Normal'], fontSize=10, textColor=colors.HexColor('#334155'), leading=14)

        elements = []
        
        # Header
        elements.append(Paragraph(f"<b>Intelligent Expertise System</b>", title_style))
        elements.append(Paragraph(f"Report Type: <b>{report_type}</b> | Generated for: <b>{user.full_name}</b> ({user.email}) | Date: <b>{datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</b>", subtitle_style))
        elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#3B82F6'), spaceAfter=15))

        if prediction:
            elements.append(Paragraph("<b>AI Model Prediction Summary</b>", heading_style))
            pred_data = [
                ["Predicted Domain", prediction.predicted_expertise],
                ["Confidence Score", f"{prediction.confidence_score}%"],
                ["ML Classifier Used", prediction.algorithm_used],
                ["Strengths Identified", prediction.strengths or "N/A"],
                ["Skill Gap Weaknesses", prediction.weaknesses or "N/A"]
            ]
            t = Table(pred_data, colWidths=[150, 380])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#F1F5F9')),
                ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor('#1E293B')),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
                ('PADDING', (0,0), (-1,-1), 6),
                ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold')
            ]))
            elements.append(t)
            elements.append(Spacer(1, 15))

        if resume_data:
            elements.append(Paragraph("<b>Resume Parsing & Skill Analysis</b>", heading_style))
            elements.append(Paragraph(f"<b>Detected Experience:</b> {resume_data.get('detected_experience', 0)} years", body_style))
            elements.append(Paragraph(f"<b>Detected Skills:</b> {', '.join(resume_data.get('detected_skills', []))}", body_style))
            elements.append(Paragraph(f"<b>Missing Domain Competencies:</b> {', '.join(resume_data.get('missing_skills', []))}", body_style))
            elements.append(Spacer(1, 15))

        if recommendations:
            elements.append(Paragraph("<b>Personalized Career Recommendations</b>", heading_style))
            rec_table_data = [["Category", "Title", "Urgency"]]
            for r in recommendations[:8]:
                rec_table_data.append([r.category, r.title, r.urgency])
            
            t2 = Table(rec_table_data, colWidths=[120, 310, 100])
            t2.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#2563EB')),
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
                ('PADDING', (0,0), (-1,-1), 6),
                ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold')
            ]))
            elements.append(t2)

        # Footer
        elements.append(Spacer(1, 20))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#94A3B8'), spaceAfter=10))
        elements.append(Paragraph("<font size=8 color='#94A3B8'>Confidential - Generated by Intelligent Expertise System AI Platform</font>", body_style))

        doc.build(elements)
        return filename

    except Exception as e:
        # Fallback simple text generator if reportlab is absent or encounters error
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(f"INTELLIGENT EXPERTISE SYSTEM - {report_type.upper()}\n")
            f.write(f"User: {user.full_name} ({user.email})\n")
            f.write(f"Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n\n")
            if prediction:
                f.write(f"Predicted Expertise: {prediction.predicted_expertise}\n")
                f.write(f"Confidence Score: {prediction.confidence_score}%\n")
                f.write(f"Strengths: {prediction.strengths}\n")
                f.write(f"Weaknesses: {prediction.weaknesses}\n")
        return filename
